name: CI

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  check:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        cmd: ['build', 'test', 'lint', 'prettier:check']
        node-version: [g'16']
    name: ${{ matrix.node-version }} - ${{ matrix.cmd }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm i -g npm@8
      - run: npm ci
      - run: npm run bootstrap
      - run: npm rebuild
      - run: npm run ${{ matrix.cmd }}
