name: CI

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  check:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        cmd: ['build', 'test', 'lint', 'prettier:check']
        node-version: ['16']
    name: ${{ matrix.node-version }} - ${{ matrix.cmd }}
    steps:
      - uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm i -g npm@8
      - run: npm ci
      - run: npm run ${{ matrix.cmd }}
  publish:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-20.04
    needs: [check]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm i -g npm@8
      - run: npm ci
      - run: npm config set //registry.npmjs.org/:_authToken=${NPM_TOKEN}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm run changeset:publish
      - run: npm run changeset:tag
      - run: git push --follow-tags
